FROM mcr.microsoft.com/playwright/python:v1.49.1-noble
WORKDIR /app
COPY pyproject.toml ./
COPY watchtower ./watchtower
RUN pip install --no-cache-dir '.[browser]'
CMD ["python", "-m", "watchtower.worker"]

